image:
  name: docker/compose:1.23.1
  entrypoint: [""]

services:
  - name: docker:dind

before_script:
  - apk add --no-cache make bash curl git
#  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build --pull --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
  only:
    - stage
  tags:
    - ims-stage-deploy-runner

deploy:
  stage: deploy
  script:
    - make deploy
  only:
    - stage
  tags:
    - ims-stage-deploy-runner
